# Generated by Django 3.2.5 on 2021-07-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answr',
            field=models.CharField(choices=[('True', 'True'), ('True', 'True')], max_length=10, verbose_name='Ответ'),
        ),
    ]
